GET http://localhost:3000/bank-accounts
### 
GET http://localhost:3000/bank-accounts/eb2a5cad-239d-4e42-87db-e9022430489f
### 
POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
  "account_number": "1244-11"
}
###
PATCH http://localhost:3000/bank-accounts/c5e310cc-23cb-4bf3-9cc3-5b4e60b0ed97
Content-Type: application/json

{
  "account_number": "1121-11"
}
###
DELETE http://localhost:3000/bank-accounts/6b7de334-f0bc-45ee-bd36-96f43aa64be2
###
POST http://localhost:3000/bank-accounts/transfer
Content-Type: application/json

{
  "from":"1111-11",
  "to":"1244-11",
  "amount":100
}